// Bu dosya `pnpm sync:content` ile üretilir; elle düzenleme.

import type { MoodId } from './moods';

export interface EsmaCore {
  number: number;
  arabic: string;
  dhikrCount: number;
  moods: MoodId[];
}

// Tirmizî sıralaması; dhikrCount ebced değeridir, baştaki "ال" hariç.
export const esmaCore: EsmaCore[] = [
  { number: 1, arabic: 'الرَّحْمَن', dhikrCount: 298, moods: ['D', 'H'] },
  { number: 2, arabic: 'الرَّحِيم', dhikrCount: 258, moods: ['D', 'E'] },
  { number: 3, arabic: 'الْمَلِك', dhikrCount: 90, moods: ['C'] },
  { number: 4, arabic: 'الْقُدُّوس', dhikrCount: 170, moods: ['B', 'C'] },
  { number: 5, arabic: 'السَّلَام', dhikrCount: 131, moods: ['B', 'F'] },
  { number: 6, arabic: 'الْمُؤْمِن', dhikrCount: 136, moods: ['F', 'B'] },
  { number: 7, arabic: 'الْمُهَيْمِن', dhikrCount: 145, moods: ['F'] },
  { number: 8, arabic: 'الْعَزِيز', dhikrCount: 94, moods: ['C', 'A'] },
  { number: 9, arabic: 'الْجَبَّار', dhikrCount: 206, moods: ['E', 'G'] },
  { number: 10, arabic: 'الْمُتَكَبِّر', dhikrCount: 662, moods: ['C'] },
  { number: 11, arabic: 'الْخَالِق', dhikrCount: 731, moods: ['G', 'A'] },
  { number: 12, arabic: 'الْبَارِئ', dhikrCount: 213, moods: ['A', 'C'] },
  { number: 13, arabic: 'الْمُصَوِّر', dhikrCount: 336, moods: ['H', 'A'] },
  { number: 14, arabic: 'الْغَفَّار', dhikrCount: 1281, moods: ['E', 'D'] },
  { number: 15, arabic: 'الْقَهَّار', dhikrCount: 306, moods: ['C', 'F'] },
  { number: 16, arabic: 'الْوَهَّاب', dhikrCount: 14, moods: ['G', 'H'] },
  { number: 17, arabic: 'الرَّزَّاق', dhikrCount: 308, moods: ['G', 'F'] },
  { number: 18, arabic: 'الْفَتَّاح', dhikrCount: 489, moods: ['A', 'H'] },
  { number: 19, arabic: 'الْعَلِيم', dhikrCount: 150, moods: ['A', 'F'] },
  { number: 20, arabic: 'الْقَابِض', dhikrCount: 903, moods: ['C', 'E'] },
  { number: 21, arabic: 'الْبَاسِط', dhikrCount: 72, moods: ['G', 'H'] },
  { number: 22, arabic: 'الْخَافِض', dhikrCount: 1481, moods: ['C'] },
  { number: 23, arabic: 'الرَّافِع', dhikrCount: 351, moods: ['H', 'E'] },
  { number: 24, arabic: 'الْمُعِزّ', dhikrCount: 117, moods: ['A', 'H'] },
  { number: 25, arabic: 'الْمُذِلّ', dhikrCount: 770, moods: ['C'] },
  { number: 26, arabic: 'السَّمِيع', dhikrCount: 180, moods: ['E', 'F'] },
  { number: 27, arabic: 'الْبَصِير', dhikrCount: 302, moods: ['E', 'C'] },
  { number: 28, arabic: 'الْحَكَم', dhikrCount: 68, moods: ['C', 'F'] },
  { number: 29, arabic: 'الْعَدْل', dhikrCount: 104, moods: ['G', 'C'] },
  { number: 30, arabic: 'اللَّطِيف', dhikrCount: 129, moods: ['B', 'E'] },
  { number: 31, arabic: 'الْخَبِير', dhikrCount: 812, moods: ['C', 'F'] },
  { number: 32, arabic: 'الْحَلِيم', dhikrCount: 88, moods: ['B', 'D'] },
  { number: 33, arabic: 'الْعَظِيم', dhikrCount: 1020, moods: ['C'] },
  { number: 34, arabic: 'الْغَفُور', dhikrCount: 1286, moods: ['D', 'E'] },
  { number: 35, arabic: 'الشَّكُور', dhikrCount: 526, moods: ['B', 'A'] },
  { number: 36, arabic: 'الْعَلِيّ', dhikrCount: 110, moods: ['H', 'C'] },
  { number: 37, arabic: 'الْكَبِير', dhikrCount: 232, moods: ['C'] },
  { number: 38, arabic: 'الْحَفِيظ', dhikrCount: 998, moods: ['F', 'B'] },
  { number: 39, arabic: 'الْمُقِيت', dhikrCount: 550, moods: ['F', 'G'] },
  { number: 40, arabic: 'الْحَسِيب', dhikrCount: 80, moods: ['F', 'C'] },
  { number: 41, arabic: 'الْجَلِيل', dhikrCount: 73, moods: ['C'] },
  { number: 42, arabic: 'الْكَرِيم', dhikrCount: 270, moods: ['D', 'A'] },
  { number: 43, arabic: 'الرَّقِيب', dhikrCount: 312, moods: ['C', 'F'] },
  { number: 44, arabic: 'الْمُجِيب', dhikrCount: 55, moods: ['H', 'E'] },
  { number: 45, arabic: 'الْوَاسِع', dhikrCount: 137, moods: ['B', 'H'] },
  { number: 46, arabic: 'الْحَكِيم', dhikrCount: 78, moods: ['C', 'B'] },
  { number: 47, arabic: 'الْوَدُود', dhikrCount: 20, moods: ['D'] },
  { number: 48, arabic: 'الْمَجِيد', dhikrCount: 57, moods: ['A'] },
  { number: 49, arabic: 'الْبَاعِث', dhikrCount: 573, moods: ['H', 'G'] },
  { number: 50, arabic: 'الشَّهِيد', dhikrCount: 319, moods: ['F', 'E'] },
  { number: 51, arabic: 'الْحَقّ', dhikrCount: 108, moods: ['H', 'C'] },
  { number: 52, arabic: 'الْوَكِيل', dhikrCount: 66, moods: ['F', 'G'] },
  { number: 53, arabic: 'الْقَوِيّ', dhikrCount: 116, moods: ['G', 'A'] },
  { number: 54, arabic: 'الْمَتِين', dhikrCount: 500, moods: ['F', 'G'] },
  { number: 55, arabic: 'الْوَلِيّ', dhikrCount: 46, moods: ['D', 'F'] },
  { number: 56, arabic: 'الْحَمِيد', dhikrCount: 62, moods: ['A', 'B'] },
  { number: 57, arabic: 'الْمُحْصِي', dhikrCount: 148, moods: ['C'] },
  { number: 58, arabic: 'الْمُبْدِئ', dhikrCount: 56, moods: ['A'] },
  { number: 59, arabic: 'الْمُعِيد', dhikrCount: 124, moods: ['H', 'G'] },
  { number: 60, arabic: 'الْمُحْيِي', dhikrCount: 68, moods: ['A', 'G'] },
  { number: 61, arabic: 'الْمُمِيت', dhikrCount: 490, moods: ['C'] },
  { number: 62, arabic: 'الْحَيّ', dhikrCount: 18, moods: ['A', 'G'] },
  { number: 63, arabic: 'الْقَيُّوم', dhikrCount: 156, moods: ['G', 'F'] },
  { number: 64, arabic: 'الْوَاجِد', dhikrCount: 14, moods: ['A'] },
  { number: 65, arabic: 'الْمَاجِد', dhikrCount: 48, moods: ['A', 'D'] },
  { number: 66, arabic: 'الْوَاحِد', dhikrCount: 19, moods: ['C', 'B'] },
  { number: 67, arabic: 'الْأَحَد', dhikrCount: 13, moods: ['C', 'B'] },
  { number: 68, arabic: 'الصَّمَد', dhikrCount: 134, moods: ['B', 'F'] },
  { number: 69, arabic: 'الْقَادِر', dhikrCount: 305, moods: ['A', 'H'] },
  { number: 70, arabic: 'الْمُقْتَدِر', dhikrCount: 744, moods: ['C', 'A'] },
  { number: 71, arabic: 'الْمُقَدِّم', dhikrCount: 184, moods: ['A', 'H'] },
  { number: 72, arabic: 'الْمُؤَخِّر', dhikrCount: 846, moods: ['B', 'H'] },
  { number: 73, arabic: 'الْأَوَّل', dhikrCount: 37, moods: ['C'] },
  { number: 74, arabic: 'الْآخِر', dhikrCount: 801, moods: ['C', 'H'] },
  { number: 75, arabic: 'الظَّاهِر', dhikrCount: 1106, moods: ['A'] },
  { number: 76, arabic: 'الْبَاطِن', dhikrCount: 62, moods: ['C'] },
  { number: 77, arabic: 'الْوَالِي', dhikrCount: 47, moods: ['F'] },
  { number: 78, arabic: 'الْمُتَعَالِي', dhikrCount: 551, moods: ['C'] },
  { number: 79, arabic: 'الْبَرّ', dhikrCount: 202, moods: ['D'] },
  { number: 80, arabic: 'التَّوَّاب', dhikrCount: 409, moods: ['E', 'D', 'H'] },
  { number: 81, arabic: 'الْمُنْتَقِم', dhikrCount: 630, moods: ['H', 'C'] },
  { number: 82, arabic: 'الْعَفُوّ', dhikrCount: 156, moods: ['D', 'E'] },
  { number: 83, arabic: 'الرَّؤُوف', dhikrCount: 286, moods: ['D', 'E'] },
  { number: 84, arabic: 'مَالِكُ الْمُلْك', dhikrCount: 212, moods: ['C'] },
  { number: 85, arabic: 'ذُو الْجَلَالِ وَالْإِكْرَام', dhikrCount: 1100, moods: ['C', 'A'] },
  { number: 86, arabic: 'الْمُقْسِط', dhikrCount: 209, moods: ['C', 'B'] },
  { number: 87, arabic: 'الْجَامِع', dhikrCount: 114, moods: ['D', 'H'] },
  { number: 88, arabic: 'الْغَنِيّ', dhikrCount: 1060, moods: ['C', 'G'] },
  { number: 89, arabic: 'الْمُغْنِي', dhikrCount: 1100, moods: ['G', 'H'] },
  { number: 90, arabic: 'الْمَانِع', dhikrCount: 161, moods: ['F'] },
  { number: 91, arabic: 'الضَّارّ', dhikrCount: 1001, moods: ['C'] },
  { number: 92, arabic: 'النَّافِع', dhikrCount: 201, moods: ['A', 'G'] },
  { number: 93, arabic: 'النُّور', dhikrCount: 256, moods: ['H', 'B'] },
  { number: 94, arabic: 'الْهَادِي', dhikrCount: 20, moods: ['H', 'F'] },
  { number: 95, arabic: 'الْبَدِيع', dhikrCount: 86, moods: ['A'] },
  { number: 96, arabic: 'الْبَاقِي', dhikrCount: 113, moods: ['E', 'H'] },
  { number: 97, arabic: 'الْوَارِث', dhikrCount: 707, moods: ['E', 'C'] },
  { number: 98, arabic: 'الرَّشِيد', dhikrCount: 514, moods: ['B', 'F'] },
  { number: 99, arabic: 'الصَّبُور', dhikrCount: 298, moods: ['E', 'B', 'G'] },
];

export const ESMA_COUNT = esmaCore.length;

export const esmaByNumber: Record<number, EsmaCore> = Object.fromEntries(
  esmaCore.map((e) => [e.number, e]),
);
